const std = @import("std");
const sphtud = @import("sphtud.zig");
const math = sphtud.math;
const Vec2 = sphtud.math.Vec2;

pub const Line2 = struct {
    a: Point2,
    b: Point2,

    pub fn dir(self: Line2) Vec2 {
        return math.normalize(self.b - self.a);
    }
};

pub const Ray2 = struct {
    start: Point2,
    dir: Vec2,
};
pub const Point2 = Vec2;

pub fn lineLineIntersection(a: Point2, a_dir: Vec2, b: Point2, b_dir: Vec2) ?Point2 {
    //
    //              b
    //             /|\
    //        (ab)/ | \ (b_dir)
    //           /  |  \
    //          / (bc)  \
    //         a----c----P -----> a_dir
    //              └─ 90°
    //
    // Given a, b, v1, v2...
    // * Get line ab (it's the only new thing we can make lol)
    // * Project that onto v1 to get c
    // * Project b_dir onto bc_dir (to get t), this will give us a small
    //   triangle with the same ratios as bPc
    // * Scale v2 according to bc / t to find bP length
    //

    // Dirty colinear check
    if (@abs(math.cross2(a_dir, b_dir)) < 1e-9) {
        return null;
    }

    const ac_len = math.dot(b - a, a_dir);
    const ac_len_v2: Vec2 = @splat(ac_len);
    const c = a + ac_len_v2 * a_dir;
    const bc = c - b;
    const bc_dir = math.normalize(bc);
    const t: Vec2 = @splat(math.length(bc) / math.dot(b_dir, bc_dir));
    const p = b + t * b_dir;
    return p;
}

test "lineLineIntersection" {
    const TestCase = struct {
        a: Point2,
        v1: Vec2,
        b: Point2,
        v2: Vec2,
        p: ?Point2,
    };

    // Full disclosure these were generated by claude and I didn't think about
    // them at all
    const test_cases: []const TestCase = &.{
        .{
            //.name = "axis-aligned perpendicular",
            //.note = "simplest sanity check",
            .a = .{ 0, 0 },
            .v1 = .{ 1, 0 },
            .b = .{ 2, 1 },
            .v2 = .{ 0, -1 },
            .p = .{ 2, 0 },
        },
        .{
            //.name = "symmetric 45-degree cross",
            //.note = "non-axis-aligned, both rays forward",
            .a = .{ 0, 0 },
            .v1 = .{ 0.7071, 0.7071 },
            .b = .{ 4, 0 },
            .v2 = .{ -0.7071, 0.7071 },
            .p = .{ 2, 2 },
        },
        .{
            //.name = "oblique angle",
            //.note = "one axis-aligned, one angled — asymmetric t values",
            .a = .{ 0, 0 },
            .v1 = .{ 1, 0 },
            .b = .{ 0, 3 },
            .v2 = .{ 0.6, -0.8 },
            .p = .{ 2.25, 0 },
        },
        .{
            //.name = "P behind b",
            //.note = "t from b is negative — P in opposite direction of v2",
            .a = .{ 0, 0 },
            .v1 = .{ 1, 0 },
            .b = .{ 2, 1 },
            .v2 = .{ 0, 1 },
            .p = .{ 2, 0 },
        },
        .{
            //.name = "P behind a",
            //.note = "t from a is negative — P in opposite direction of v1",
            .a = .{ 3, 0 },
            .v1 = .{ 1, 0 },
            .b = .{ 0, 2 },
            .v2 = .{ 0, -1 },
            .p = .{ 0, 0 },
        },
        .{
            //.name = "parallel lines",
            //.note = "dot(v2, bc_hat) == 0 — expect divide-by-zero / no intersection",
            .a = .{ 0, 0 },
            .v1 = .{ 1, 0 },
            .b = .{ 0, 1 },
            .v2 = .{ 1, 0 },
            .p = null,
        },
    };

    for (test_cases) |tc| {
        const p = lineLineIntersection(tc.a, tc.v1, tc.b, tc.v2);
        if (tc.p) |tcp| {
            try std.testing.expectApproxEqAbs(tcp[0], p.?[0], 0.0001);
            try std.testing.expectApproxEqAbs(tcp[1], p.?[1], 0.0001);
        } else {
            try std.testing.expectEqual(null, p);
        }
    }
}

pub fn rayLineIntersect(ray: Ray2, line: Line2) ?Point2 {
    const line_vec = line.b - line.a;
    const line_dir = math.normalize(line_vec);
    const p = lineLineIntersection(ray.start, ray.dir, line.a, line_dir) orelse return null;

    const p_behind_ray = math.dot(p - ray.start, ray.dir) < 0;
    if (p_behind_ray) return null;

    // P may be outside the bounds of our line
    // if we project onto the line dir we can see if it's outside the bounds
    const proj = math.dot(p - line.a, line_vec) / math.dot(line_vec, line_vec);
    if (proj < 0 or proj > 1) return null;
    return p;
}

pub const Circle = struct {
    center: Point2,
    radius: f32,
};

pub fn rayCircleIntersection(r: Ray2, c: Circle, ret_buf: *[2]Point2) []Point2 {
    //
    //                          -------------
    //                      ----             ----
    //                   ---                     ---
    //                 --                           --
    //                -                               -
    //               -                                 -
    //              -                                   -
    //             |                                     |
    //             |                  center             |
    //             -                  *                  -
    //             |                  |                  |
    //             |                  |perp              |
    //              -                 |                 -
    //               - a              |              b -
    //     start *----*---------------*---------------*------> dir
    //                 --             midpoint      --
    //                   ---                     ---
    //                      ----             ----
    //                          -------------
    //
    // Given a ray starting at start, and point in (normalized) dir, find
    // intersection points a and b
    //
    // AFAICT, an orthogonal line to the ray that goes through the center of
    // the circle is ALWAYS the midpoint of a and b along the ray. We can
    // easily find this point with a dot product of center - start onto the ray
    //
    // From here we can just pythagoras with the radius to find the distance
    // from the midpoint to the intersections and we have our answer

    std.debug.assert(1.0 - sphtud.math.length2(r.dir) < 1e-6);

    const to_midpoint = sphtud.math.dot(c.center - r.start, r.dir);
    const midpoint = r.start + r.dir * Vec2{ to_midpoint, to_midpoint };

    const r_2 = c.radius * c.radius;
    const perp = midpoint - c.center;
    const perp_len_2 = sphtud.math.length2(perp);

    if (perp_len_2 > r_2) {
        return &.{};
    }

    const offs = @sqrt(r_2 - perp_len_2);

    const offs_v = Vec2{ offs, offs };
    const a = midpoint + r.dir * offs_v;
    const b = midpoint - r.dir * offs_v;

    var ret = std.ArrayList(Vec2).initBuffer(ret_buf);
    if (sphtud.math.dot(a - r.start, r.dir) >= 0) {
        ret.appendBounded(a) catch unreachable;
    }

    if (sphtud.math.dot(b - r.start, r.dir) >= 0) {
        ret.appendBounded(b) catch unreachable;
    }

    return ret.items;
}

pub const Ellipse = struct {
    center: Point2,
    rx: f32,
    ry: f32,
    // radians
    rotation: f32,
};

pub fn ellipseToCircle(e: Ellipse) math.Transform {
    return sphtud.math.Transform.translate(-e.center[0], -e.center[1])
        .then(sphtud.math.Transform.rotate(-e.rotation))
        .then(sphtud.math.Transform.scale(1 / e.rx, 1 / e.ry));
}

pub fn ellipseFromCircle(e: Ellipse) math.Transform {
    return sphtud.math.Transform.scale(e.rx, e.ry)
        .then(.rotate(e.rotation))
        .then(.translate(e.center[0], e.center[1]));
}

pub fn rayEllipseIntersection(
    ray: Ray2,
    e: Ellipse,
    ret_buf: *[2]Vec2,
) []sphtud.math.Vec2 {
    const to_circle = ellipseToCircle(e);

    const old_end = ray.start + ray.dir;
    const new_end = to_circle.apply2(old_end);
    const new_start = to_circle.apply2(ray.start);
    const new_dir = sphtud.math.normalize(new_end - new_start);

    const ret = sphtud.geometry.rayCircleIntersection(
        .{ .start = new_start, .dir = new_dir },
        .{
            .center = .{ 0, 0 },
            .radius = 1,
        },
        ret_buf,
    );

    const from_circle = ellipseFromCircle(e);

    for (ret) |*r| {
        r.* = from_circle.apply2(r.*);
    }

    return ret;
}
